version: '3.8'

services:
  nestjs-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3030:3030'
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:prod
